manifest:
  remotes:
    - name: zmkfirmware # Official ZMK
      url-base: https://github.com/zmkfirmware
    - name: personal # Personal patched variant of ZMK
      url-base: https://github.com/maverick1872
    - name: urob # Patched variant of ZMK
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
  self:
    path: config
