on: [push]
# on: [push, pull_request, workflow_dispatch]
#
# jobs:
#   build:
#     uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
jobs:
  build:
    name: Build Corne Firmware
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: corne-firmware
    #   build_matrix_path: corne/build.yaml
    #   config_path: corne
