# Simple workflow for drawing the keymap and deploying static content to GitHub Pages
name: Draw keymap

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/draw.yml"
      - "config/*.keymap"
      - "config/*.dtsi"
      - "keymap_drawer.config.yaml"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "keymap"
  cancel-in-progress: true

jobs:
  draw:
    name: Generate & Commit keymap
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap" # path to the keymaps to parse
      west_config_path: './config/'
      output_folder: "svg" # path to save produced SVGs
      commit_message: "chore(draw): regenerate keymap"
      fail_on_error: true
      debug_mode: false
